on:
  push:
    branches:
      - main
      - yazaki
    paths:
      - 'thesis.tex'
      - 'sections/*'
      - '.github/workflows/build.yaml'
      - 'export.bib'

env:
  FILENAME: thesis

jobs:
  release:
    runs-on: ubuntu-latest
    container: texlive/texlive
    steps:
      - name: Checkout git repo
        uses: actions/checkout@v4

      - name: Build a PDF file by latexmk
        run: latexmk $FILENAME.tex

      - name: Set tagname
        run: echo "TAG_NAME=$(date +'%Y%m%d%H%M')" >> $GITHUB_ENV

      - name: Create a release
        uses: softprops/action-gh-release@v2
        with:
          files: ${{ env.FILENAME }}.pdf
          tag_name: ${{ env.TAG_NAME }}
